version: '3.8'

services:
  ems_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  ems_auth_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_AUTH_NAME}
    ports:
      - "3307:3307"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    

volumes:
  mysql_data:
  mysql_auth_data:
