version: '3.8'

services:
  mysql:
    build:
      context: ./database
      dockerfile: ${DOCKERFILE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./database/.env.${ENVIRONMENT}

volumes:
  mysql_data:
