server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true